//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Database_First.Models
{
    [Table("T_Users")]
    public class T_Users
    {
        [Key]
        public int UserId { get; set; }
        [Display(Name = "نام")]
        [Required(ErrorMessage = "فیلد نام نباید خالی باشد")]
        public string Name { get; set; }
        [Display(Name = "فامیل")]
        [Required(ErrorMessage = "فیلد {0} نباید خالی باشد")]
        public string Family { get; set; }
        [Display(Name = "ایمیل")]
        [EmailAddress(ErrorMessage = "قالب ایمیل نا معتبر است")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Display(Name = "موبایل")]
        [Required(ErrorMessage = "فیلد {0} نباید خالی باشد")]
        [DataType(DataType.PhoneNumber)]
        public string MobileNumber { get; set; }
        [Display(Name = "رمز عبور")]
        [Required(ErrorMessage = "فیلد {0} نباید خالی باشد")]
        [DataType(DataType.Password)]
        [StringLength(12, MinimumLength = 6, ErrorMessage = "لطفا تعداد حروف بین 6 تا 12 حرف باشد")]
        public string Password { get; set; }
        [Display(Name = "تصویر")]
        public string ImageName { get; set; }
        [Display(Name = "آدرس")]
        [DataType(DataType.MultilineText)]
        
        public string Address { get; set; }
        [Display(Name = "وضعیت تاهل")]
        public bool? Marital { get; set; }
        [Display(Name = "فعال/غیرفعال")]
        [Required(ErrorMessage = "فیلد {0} نباید خالی باشد")]
        public bool IsActive { get; set; }
        [Display(Name = "تاریخ ثبت نام")]
        [Required(ErrorMessage = "فیلد {0} نباید خالی باشد")]
        [DisplayFormat(DataFormatString = "{0:dddd, dd MMMM yyyy}")]
        public DateTime RegisterDate { get; set; }
    }
}
